# Generated by Django 3.0.7 on 2020-07-10 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='images',
        ),
    ]
