# Generated by Django 3.0.7 on 2020-07-24 07:15

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20200722_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.post_img_path),
        ),
    ]
