# Generated by Django 3.0.7 on 2020-07-22 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20200721_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyread',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_read', to='stories.Story'),
        ),
    ]
