# Generated by Django 3.0.7 on 2020-07-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_auto_20200722_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='caption',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='story_image'),
        ),
    ]
