# Generated by Django 3.0.7 on 2020-07-27 10:19

from django.db import migrations, models
import stories.models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_auto_20200724_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(upload_to=stories.models.story_img_path),
        ),
    ]
