# Generated by Django 3.0.7 on 2020-07-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='related_type',
            field=models.CharField(choices=[('follow', 'Follow'), ('block', 'Block')], max_length=10),
        ),
    ]
